/**
 * server/src/routes/report.js
 * GET /api/report/:jobId         — returns the full report as JSON
 * GET /api/report/:jobId/markdown — returns a Markdown-formatted export
 *
 * Reports are read back from the job store rather than held in memory, because
 * on Vercel the invocation that produced them is long gone by the time the user
 * clicks "Export".
 */

const express = require('express');
const { getJob, getReport } = require('../store/jobs');

const router = express.Router();

/** Load a finished report, or explain why it cannot be served. */
async function loadReport(req, res) {
  const job = await getJob(req.params.jobId);
  if (!job) {
    res.status(404).json({ error: 'Job not found or expired.' });
    return null;
  }
  if (job.status === 'error') {
    res.status(422).json({ error: job.error || 'Analysis failed.' });
    return null;
  }
  if (job.status !== 'done') {
    res.status(202).json({ status: job.status });
    return null;
  }
  const report = await getReport(job.id);
  if (!report) {
    res.status(410).json({ error: 'Report is no longer available for this job.' });
    return null;
  }
  return report;
}

// ── GET /api/report/:jobId ─────────────────────────────────────────────────────
router.get('/:jobId', async (req, res, next) => {
  try {
    const report = await loadReport(req, res);
    if (report) res.json(report);
  } catch (err) {
    next(err);
  }
});

// ── GET /api/report/:jobId/markdown ──────────────────────────────────────────
router.get('/:jobId/markdown', async (req, res, next) => {
  try {
    const report = await loadReport(req, res);
    if (!report) return;

    const md = buildMarkdown(report);
    res.setHeader('Content-Type', 'text/markdown; charset=utf-8');
    res.setHeader('Content-Disposition', `attachment; filename="modernization-report-${req.params.jobId.slice(0, 8)}.md"`);
    res.send(md);
  } catch (err) {
    next(err);
  }
});

// ── Markdown builder ──────────────────────────────────────────────────────────

/**
 * Convert the report object into a Markdown string.
 * @param {object} report
 * @returns {string}
 */
function buildMarkdown(report) {
  const lines = [];
  const { meta, healthScore, executiveSummary, risks, suggestions, refactorOrder } = report;

  lines.push(`# Legacy Code Modernization Report`);
  lines.push(`\n> Generated: ${new Date(meta.generatedAt).toLocaleString()}`);
  lines.push(`> Job ID: \`${meta.jobId}\``);
  lines.push(`> Files analysed: **${meta.fileCount}** (${meta.languages.join(', ')})`);

  lines.push(`\n## Overall Health Score: ${healthScore}/100`);
  const bar = '█'.repeat(Math.round(healthScore / 10)) + '░'.repeat(10 - Math.round(healthScore / 10));
  lines.push(`\`${bar}\` ${healthScore}%`);

  if (executiveSummary) {
    lines.push(`\n## Executive Summary\n\n${executiveSummary}`);
  }

  // Risk table
  lines.push(`\n## Risk Summary\n`);
  lines.push(`| Severity | Count |`);
  lines.push(`|----------|-------|`);
  ['high', 'medium', 'low'].forEach(sev => {
    const count = risks.filter(r => r.severity === sev).length;
    lines.push(`| ${sev.charAt(0).toUpperCase() + sev.slice(1)} | ${count} |`);
  });

  // Prioritised file list
  lines.push(`\n## Risky Files (Prioritised)\n`);
  for (const risk of risks) {
    const badge = risk.severity === 'high' ? '🔴' : risk.severity === 'medium' ? '🟡' : '🟢';
    lines.push(`### ${badge} \`${risk.file}\``);
    lines.push(`- **Severity**: ${risk.severity}`);
    lines.push(`- **Language**: ${risk.language}`);
    lines.push(`\n**Issues detected:**`);
    for (const issue of risk.issues) {
      lines.push(`- ${issue}`);
    }
    lines.push('');
  }

  // Suggested refactor order
  if (refactorOrder.length > 0) {
    lines.push(`\n## Suggested Refactor Order\n`);
    lines.push(`_Files with fewer dependents are listed first — safest to modify without cascading breakage._\n`);
    refactorOrder.forEach((f, i) => lines.push(`${i + 1}. \`${f}\``));
  }

  // AI Modernization Suggestions
  if (suggestions.length > 0) {
    lines.push(`\n## AI Modernization Suggestions\n`);
    for (const s of suggestions) {
      lines.push(`### \`${s.file}\`\n`);
      lines.push(s.suggestion);
      if (s.diff) {
        lines.push(`\n${s.diff}`);
      }
      lines.push('');
    }
  }

  lines.push(`\n---\n_Report generated by Legacy Code Modernizer_`);
  return lines.join('\n');
}

module.exports = router;
